{% set version = "4.0" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscaffold/PyScaffold-{{ version }}.tar.gz
  sha256: 7012ae5f9c95b910a39a099824104dc888beb932de86b07514882f3511bc6c74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - configupdater

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help

about:
  home: http://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Template tool for putting up the scaffold of a Python project

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
