{% set version = "3.3.1" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscaffold/PyScaffold-{{ version }}.tar.gz
  sha256: 1c3a2b76e60319b6ffc2a8b54e240382109c6241576bf0a47ea476c7194f6a69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help

about:
  home: http://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Template tool for putting up the scaffold of a Python project

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
