{% set version = "4.0.1rc1" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscaffold/PyScaffold-{{ version }}.tar.gz
  sha256: 4d99218ca3cbae065466ec8627f2122d4c0e95b245ba6827369121a44b40e296

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm >=5
  run:
    - python >=3
    - importlib-metadata
    - appdirs >=1.4.4,<2
    - configupdater >=2.0,<3
    - setuptools >=46.1.0
    - setuptools_scm >=5
    - tomlkit >=0.7.0,<2
    - packaging >=20.7

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - pip check
    - putup --help
    - pytest
  requires:
    - pip
    - pytest
    - pytest-cov
    - git
    - tox
    - twine
    - pre-commit
  source_files:
    - tests

about:
  home: http://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Template tool for putting up the scaffold of a Python project

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
