{% set version = "3.0.2" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscaffold/PyScaffold-{{ version }}.tar.gz
  sha256: 639a9266a1c6c399d87d7a0a6ccf8bd0132c562086d2a343a1d871b25d2a3203

build:
  noarch: python
  number: 0
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help

about:
  home: http://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Template tool for putting up the scaffold of a Python project.'

extra:
  recipe-maintainers:
    - ocefpaf
