{% set version = "2.4.2" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  fn: PyScaffold-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyscaffold/pyscaffold-{{ version }}.tar.gz
  sha256: 746f9aa37ac31b372bb3b960c8516f4f0d3bad6c8c2d32b48d0572f507f07122

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 1
  preserve_egg_dir: True
  entry_points:
    - putup=pyscaffold.cli:run


requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.7
    - six
    - pbr >=1.6
  run:
    - python
    - setuptools_scm >=1.7
    - six
    - pbr >=1.6

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help

about:
  home: http://pyscaffold.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Template tool for putting up the scaffold of a Python project.'

extra:
  recipe-maintainers:
    - ocefpaf
