{% set version = "3.2.2" %}

package:
  name: pyscaffold
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyscaffold/PyScaffold-{{ version }}.tar.gz
  sha256: 931679218ecdf64b0cabcfcda426a15595fc87b7ec0afc27d133dc821190c10e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - putup = pyscaffold.cli:run


requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools

test:
  imports:
    - pyscaffold
    - pyscaffold.templates
  commands:
    - putup --help

about:
  home: http://pyscaffold.org/
  license: MIT
  license_file: LICENSE.txt
  summary: 'Template tool for putting up the scaffold of a Python project'

extra:
  recipe-maintainers:
    - ocefpaf
