# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=34
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kMytDatssvO/xhNNkX36owCn1WfDa77tZriP35mdO0KKhdhLrnB3bqVAc0RalPsXRZSFnXapPafRfPzMXO/IaGg+ZVhIGZ3/7DY8yHbnojnEFmt8XBXQeYYdzRuYeJVJc02nYIi8XOo0RlO5PIiiBADogc0I/UE7hycUE+kLX/1GqLLaMVTDo1MZZgoZ146LpgRl665xnkD1jQk9wNK4xChgNhyKsqooEAV4LKL52yqqgtMZDfuZmP87ubMO4Dw8/I5FBjdN3ZaPmXI/WAnhNuqpInUB6OhDIzf15tstQpXaegSNSz5mov6wyepDh5jK+5ES4gz/Ln0WLn9mFxPApm0mu1GRYTulMNZknxXTzpykzGu4TUU+LGa9I0epRiqb29z4x+HnqfS14gMYHo9iURqeXTveO/75kokxfcddzz7G6JUBFGj/2xu9Qtr+2f9j1fGE6FXkhQ6K5bT7PbspZ//oejoalf2TaWXbRom2Eps4rXZAZrp/fkq+motydUjbu6mR5sQQ81BaCLnc1bWROxozrLx9PXgHI3u/pnQs3nSPyHkyZHNiuAsKatxrOQJK/Nm1ayuQuXEBZLpwOiHHlXcq3qM9Zy9Fr2c3jCybzbu+jYjF5Fuu+6TooV1q3To7/uSGuvxuL2TaXbblOX0rLqUb9grNNvNlWCjLOnwMuJk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
