travis:
  secure:
    BINSTAR_TOKEN: kMytDatssvO/xhNNkX36owCn1WfDa77tZriP35mdO0KKhdhLrnB3bqVAc0RalPsXRZSFnXapPafRfPzMXO/IaGg+ZVhIGZ3/7DY8yHbnojnEFmt8XBXQeYYdzRuYeJVJc02nYIi8XOo0RlO5PIiiBADogc0I/UE7hycUE+kLX/1GqLLaMVTDo1MZZgoZ146LpgRl665xnkD1jQk9wNK4xChgNhyKsqooEAV4LKL52yqqgtMZDfuZmP87ubMO4Dw8/I5FBjdN3ZaPmXI/WAnhNuqpInUB6OhDIzf15tstQpXaegSNSz5mov6wyepDh5jK+5ES4gz/Ln0WLn9mFxPApm0mu1GRYTulMNZknxXTzpykzGu4TUU+LGa9I0epRiqb29z4x+HnqfS14gMYHo9iURqeXTveO/75kokxfcddzz7G6JUBFGj/2xu9Qtr+2f9j1fGE6FXkhQ6K5bT7PbspZ//oejoalf2TaWXbRom2Eps4rXZAZrp/fkq+motydUjbu6mR5sQQ81BaCLnc1bWROxozrLx9PXgHI3u/pnQs3nSPyHkyZHNiuAsKatxrOQJK/Nm1ayuQuXEBZLpwOiHHlXcq3qM9Zy9Fr2c3jCybzbu+jYjF5Fuu+6TooV1q3To7/uSGuvxuL2TaXbblOX0rLqUb9grNNvNlWCjLOnwMuJk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
