travis:
  secure:
    BINSTAR_TOKEN: HwoVSGyXsnWa5gR/X9YsYAeXFcaCfv9+C4gyc2kewXPriZ6Yq7NXOoVsxu9Yt59/HwVhFbqdQgH5nWCHNpeySa4XwStIuQWruoDeIHUfKrR24N8isJ1YBjmPE/1ncuGGuTvfAmCfoVIBC8nVP1GpKc/p+vhHsVg+VYd/CO7X4Uub2S63dsggqBoBRvIgrTp5O230INgAJImxCJyR+u0HrQU1jnImx+soQQREgDTFzz4s5did0WS+TewJbmTxC6xdppXnSjySFa7yTd4sv/DdqXpW6RFGE6jelBnM7F2TZmpbFKAmTdFErjnjxSwdyq5YJr505LofP6XchKuYR/Tvgs/T6oRCGTN/ud5ApPtAbCCb0InCVTxN7FDPODBt/T978frpD+TnaJKNmb8FkDOdB9JlVN3nW9sNg/VYyixzNTtgjcq5GtyuxMgkiVwngDx+MNaiBBDxmYJ3X1+3dplT/JzCmMzCLeEveT/mIE0nJZI05ksS8667QQUppOB3wGo3GGddta0u+I0v/AQ6520juk8XyZWWAPzPbWNN9wUTPoQkRk+PPEPupjMxgKmc/E2oIk9IDXvGsHTXDf6cKZJYwRAojEOkYKpvQgFmcqCKhaDgl2OG/QAWyL0F7mBxVBvcZNKPZIzNhAn3oU+4noS4gs4M9A77sQBrG2dM/4Ib1ic=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
